version: 2.1 # use CircleCI 2.1

common_env: &common_env
  BUNDLE_CLEAN: 'true'
  BUNDLE_JOBS: 3
  BUNDLE_RETRY: 3
  BUNDLE_PATH: vendor/bundle
  RAILS_ENV: test
  TZ: 'Asia/Tokyo'

executors:
  ruby-2-7:
    docker:
      - image: circleci/ruby:2.7
    environment:
      <<: *common_env
  node-browsers-2-5:
    docker:
      - image: circleci/ruby:2.5-node-browsers
    environment:
      <<: *common_env
  node-browsers-2-6:
    docker:
      - image: circleci/ruby:2.6-node-browsers
    environment:
      <<: *common_env
  node-browsers-2-7:
    docker:
      - image: circleci/ruby:2.7-node-browsers
    environment:
      <<: *common_env

commands:
  update_rubygems:
    steps:
      - run:
          name: Setup RubyGems and Bundler
          command: |-
            sudo gem update --system
  which_bundler:
    steps:
      - run:
          name: Which bundler?
          command: bundle -v
  which_ruby:
    steps:
      - run:
          name: Which Ruby?
          command: ruby -v
  # Restore bundle cache
  # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
  restore_gems:
    parameters:
      ruby-version:
        type: string
    steps:
      - restore_cache:
          keys:
            - bundle-v2-<< parameters.ruby-version >>-{{ checksum "Gemfile.lock" }}
            - bundle-v2-
  # Install Ruby dependencies
  install_gems:
    steps:
      - run:
          name: Bundle Install
          command: bundle check || bundle install
  # Store bundle cache for Ruby dependencies
  save_gems:
    parameters:
      ruby-version:
        type: string
    steps:
      - save_cache:
          key: bundle-v2-<< parameters.ruby-version >>-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  setup_database:
    steps:
      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace
  minitest:
    steps:
      - run:
          name: Run minitest
          command: |-
            bundle exec rails test
  system_test:
    steps:
      - run:
          name: Run system test
          command: |-
            bundle exec rails test:system
      - store_artifacts:
          path: tmp/screenshots
  store_test_reports:
    steps:
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: test/reports

jobs: # a collection of steps
  brakeman:
    executor: ruby-2-7
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.7'
      - install_gems
      - save_gems:
          ruby-version: '2.7'
      - run:
          name: Run Brakeman
          command: |-
            bundle exec brakeman
  minitest-2-5:
    executor: node-browsers-2-5
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.5'
      - install_gems
      - save_gems:
          ruby-version: '2.5'
      - setup_database
      - minitest
      - store_test_reports
  system-test-2-5:
    executor: node-browsers-2-5
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.5'
      - install_gems
      - save_gems:
          ruby-version: '2.5'
      - setup_database
      - system_test
      - store_test_reports
  minitest-2-6:
    executor: node-browsers-2-6
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.6'
      - install_gems
      - save_gems:
          ruby-version: '2.6'
      - setup_database
      - minitest
      - store_test_reports
  system-test-2-6:
    executor: node-browsers-2-6
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.6'
      - install_gems
      - save_gems:
          ruby-version: '2.6'
      - setup_database
      - system_test
      - store_test_reports
  minitest-2-7:
    executor: node-browsers-2-7
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.7'
      - install_gems
      - save_gems:
          ruby-version: '2.7'
      - setup_database
      - minitest
      - store_test_reports
  system-test-2-7:
    executor: node-browsers-2-7
    steps:
      - checkout
      - update_rubygems
      - which_bundler
      - which_ruby
      - restore_gems:
          ruby-version: '2.7'
      - install_gems
      - save_gems:
          ruby-version: '2.7'
      - setup_database
      - system_test
      - store_test_reports

workflows:
  version: 2
  brakeman:
    jobs:
      - brakeman
  ruby-2.5-test:
    jobs:
      - minitest-2-5
      - system-test-2-5
  ruby-2.6-test:
    jobs:
      - minitest-2-6
      - system-test-2-6
  ruby-2.7-test:
    jobs:
      - minitest-2-7
      - system-test-2-7
